version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: adoptame-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: adoptame

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    container_name: adoptame-api
    ports:
      - '3001:3001'
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - /app/apps/api/node_modules
      - /app/packages/schemas/dist
      - /app/packages/types/dist
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/adoptame
    depends_on:
      - mongodb
    env_file:
      - ./apps/api/.env

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    container_name: adoptame-web
    ports:
      - '3000:3000'
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/apps/web/node_modules
      - /app/apps/web/.next
      - /app/packages/schemas/dist
      - /app/packages/types/dist
    env_file:
      - ./apps/web/.env
    depends_on:
      - api

volumes:
  mongo-data:
