// Datos de seed para desarrollo local
// Imágenes placeholder de Unsplash (libres de uso)

export const USERS_DATA = [
  {
    name: 'Admin Adoptame',
    email: 'admin@adoptame.app',
    password: 'Admin1234!',
    role: 'admin' as const,
  },
  {
    name: 'Laura Martínez',
    email: 'fundacion1@adoptame.app',
    password: 'Fund1234!',
    role: 'foundation' as const,
  },
  {
    name: 'Carlos Herrera',
    email: 'fundacion2@adoptame.app',
    password: 'Fund1234!',
    role: 'foundation' as const,
  },
  {
    name: 'María González',
    email: 'adoptante@adoptame.app',
    password: 'User1234!',
    role: 'adopter' as const,
  },
]

export const FOUNDATIONS_DATA = [
  {
    userEmail: 'fundacion1@adoptame.app',
    name: 'Huellitas Felices Bogotá',
    description:
      'Somos una fundación sin ánimo de lucro ubicada en Bogotá, Colombia. Rescatamos perros y gatos en situación de calle, los rehabilitamos y los entregamos en adopción responsable. Llevamos más de 5 años trabajando por el bienestar animal.',
    city: 'Bogotá',
    country: 'Colombia',
    phone: '+573001234567',
    website: 'https://huellitasfelices.org',
    instagram: '@huellitasfelices',
    facebook: 'huellitasfelicesbogota',
    verified: true,
    donationLinks: {
      nequi: '3001234567',
      paypal: 'https://paypal.me/huellitasfelices',
    },
  },
  {
    userEmail: 'fundacion2@adoptame.app',
    name: 'Patitas al Rescate Medellín',
    description:
      'Fundación dedicada al rescate y adopción de animales en Medellín y el Área Metropolitana. Contamos con hogar de paso para más de 30 animales simultáneamente. Creemos en la adopción responsable y el seguimiento post-adopción.',
    city: 'Medellín',
    country: 'Colombia',
    phone: '+573109876543',
    instagram: '@patitasalrescate',
    verified: true,
    donationLinks: {
      nequi: '3109876543',
      daviplata: '3109876543',
    },
  },
]

export const PETS_DATA = [
  {
    foundationEmail: 'fundacion1@adoptame.app',
    name: 'Luna',
    species: 'dog' as const,
    breed: 'Labrador Mestiza',
    age: 'young' as const,
    size: 'medium' as const,
    sex: 'female' as const,
    color: 'Dorada',
    description:
      'Luna es una perra mestiza de aproximadamente 2 años, muy cariñosa y juguetona. Le encanta correr en el parque y es excelente con los niños. Llegó a nosotros después de ser rescatada de la calle en condiciones de desnutrición. Ya está completamente recuperada y lista para encontrar su hogar definitivo.',
    story:
      'La encontramos en el barrio Chapinero, asustada y desnutrida. Después de 3 meses de recuperación y amor, Luna es una perrita diferente: feliz, sana y llena de vida.',
    photos: [
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80',
      'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=800&q=80',
    ],
    compatibleWithKids: true,
    compatibleWithPets: true,
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    urgent: false,
    city: 'Bogotá',
    country: 'Colombia',
  },
  {
    foundationEmail: 'fundacion1@adoptame.app',
    name: 'Milo',
    species: 'dog' as const,
    breed: 'Beagle Mestizo',
    age: 'puppy' as const,
    size: 'small' as const,
    sex: 'male' as const,
    color: 'Tricolor',
    description:
      'Milo es un cachorro de 4 meses lleno de energía y curiosidad. Le encanta explorar todo, jugar con pelotas y recibir cariño. Es ideal para una familia activa que quiera un compañero fiel desde pequeño.',
    photos: [
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&q=80',
    ],
    compatibleWithKids: true,
    compatibleWithPets: true,
    vaccinated: true,
    sterilized: false,
    dewormed: true,
    urgent: false,
    city: 'Bogotá',
    country: 'Colombia',
  },
  {
    foundationEmail: 'fundacion1@adoptame.app',
    name: 'Bella',
    species: 'cat' as const,
    breed: 'Doméstico Corto',
    age: 'adult' as const,
    size: 'small' as const,
    sex: 'female' as const,
    color: 'Naranja y blanco',
    description:
      'Bella es una gata adulta de 3 años, tranquila e independiente. Perfecta para apartamento. Le gusta tomar el sol, observar por la ventana y recibir caricias cuando ella lo decide. Convive bien con otras gatas.',
    photos: [
      'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&q=80',
      'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&q=80',
    ],
    compatibleWithKids: false,
    compatibleWithPets: true,
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    urgent: false,
    city: 'Bogotá',
    country: 'Colombia',
  },
  {
    foundationEmail: 'fundacion1@adoptame.app',
    name: 'Rex',
    species: 'dog' as const,
    breed: 'Pastor Alemán Mestizo',
    age: 'adult' as const,
    size: 'large' as const,
    sex: 'male' as const,
    color: 'Negro y café',
    description:
      'Rex es un perro grande, inteligente y leal. Necesita una familia con espacio y experiencia con razas grandes. Es muy protector y aprende comandos rápidamente. No se lleva bien con otros perros machos.',
    photos: [
      'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=800&q=80',
    ],
    compatibleWithKids: true,
    compatibleWithPets: false,
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    urgent: true,
    city: 'Bogotá',
    country: 'Colombia',
  },
  {
    foundationEmail: 'fundacion2@adoptame.app',
    name: 'Coco',
    species: 'dog' as const,
    breed: 'Chihuahua Mestizo',
    age: 'senior' as const,
    size: 'small' as const,
    sex: 'male' as const,
    color: 'Café claro',
    description:
      'Coco tiene 8 años y mucho amor por dar. Es tranquilo, cariñoso y agradecido. Los perros senior son los más ignorados en adopción, pero también los más agradecidos. Ideal para una persona mayor o un hogar tranquilo.',
    story:
      'Su dueño anterior falleció y Coco quedó solo. Merece pasar sus años dorados en un hogar lleno de amor.',
    photos: [
      'https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=800&q=80',
    ],
    compatibleWithKids: false,
    compatibleWithPets: true,
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    urgent: true,
    city: 'Medellín',
    country: 'Colombia',
  },
  {
    foundationEmail: 'fundacion2@adoptame.app',
    name: 'Nala',
    species: 'cat' as const,
    breed: 'Siamés Mestiza',
    age: 'young' as const,
    size: 'small' as const,
    sex: 'female' as const,
    color: 'Crema con puntas oscuras',
    description:
      'Nala es una gata joven de 1 año, muy expresiva y comunicativa. Le encanta jugar, perseguir juguetes y estar cerca de las personas. Es la primera en saludar cuando llegas a casa.',
    photos: [
      'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=800&q=80',
      'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800&q=80',
    ],
    compatibleWithKids: true,
    compatibleWithPets: true,
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    urgent: false,
    city: 'Medellín',
    country: 'Colombia',
  },
  {
    foundationEmail: 'fundacion2@adoptame.app',
    name: 'Thor',
    species: 'dog' as const,
    breed: 'Pitbull Mestizo',
    age: 'young' as const,
    size: 'large' as const,
    sex: 'male' as const,
    color: 'Gris moteado',
    description:
      'Thor es un perro de 2 años, fuerte pero muy amoroso. Contrario al estereotipo de su raza, es calmado, obediente y le encantan los mimos. Ha pasado por obediencia básica. Necesita una familia responsable que entienda que los Pitbull son tan buenos como su crianza.',
    photos: [
      'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&q=80',
    ],
    compatibleWithKids: true,
    compatibleWithPets: false,
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    urgent: false,
    city: 'Medellín',
    country: 'Colombia',
  },
  {
    foundationEmail: 'fundacion2@adoptame.app',
    name: 'Mochi',
    species: 'cat' as const,
    breed: 'Angora Mestizo',
    age: 'puppy' as const,
    size: 'small' as const,
    sex: 'male' as const,
    color: 'Blanco',
    description:
      'Mochi es un gatito de 3 meses, blanco como la nieve y con los ojos más azules que verás. Es juguetón, curioso y adora explorar. Perfecto para quien quiera ver crecer a su compañero desde pequeño.',
    photos: [
      'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=800&q=80',
    ],
    compatibleWithKids: true,
    compatibleWithPets: true,
    vaccinated: true,
    sterilized: false,
    dewormed: true,
    urgent: false,
    city: 'Medellín',
    country: 'Colombia',
  },
  {
    foundationEmail: 'fundacion1@adoptame.app',
    name: 'Simba',
    species: 'cat' as const,
    breed: 'Doméstico Largo',
    age: 'adult' as const,
    size: 'small' as const,
    sex: 'male' as const,
    color: 'Naranja atigrado',
    description:
      'Simba es un gato de 4 años con mucha personalidad. Le gusta el sol, la comida y hacer lo que quiere. No es muy manejable con extraños al principio, pero una vez que te gana la confianza, es el compañero más fiel.',
    photos: [
      'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&q=80',
    ],
    compatibleWithKids: false,
    compatibleWithPets: false,
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    urgent: false,
    city: 'Bogotá',
    country: 'Colombia',
  },
  {
    foundationEmail: 'fundacion1@adoptame.app',
    name: 'Lola',
    species: 'dog' as const,
    breed: 'Salchicha Mestiza',
    age: 'adult' as const,
    size: 'small' as const,
    sex: 'female' as const,
    color: 'Café oscuro',
    description:
      'Lola es una perra pequeña de 3 años, perfecta para apartamento. Es tranquila, cariñosa y le encanta dormir. Sale bien en correa y se lleva bien con perros pequeños. Ideal para quien busca un compañero sin demasiada energía.',
    photos: [
      'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80',
      'https://images.unsplash.com/photo-1537151672256-6b4428d32c03?w=800&q=80',
    ],
    compatibleWithKids: true,
    compatibleWithPets: true,
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    urgent: false,
    city: 'Bogotá',
    country: 'Colombia',
  },
]

export const ADOPTION_REQUESTS_DATA = [
  {
    adopterEmail: 'adoptante@adoptame.app',
    petName: 'Luna',
    status: 'pending' as const,
    housingType: 'house' as const,
    hasYard: true,
    hasPets: false,
    hasChildren: true,
    experience: 'some' as const,
    workSchedule: 'Trabajo desde casa 3 días a la semana. Los otros 2 días salgo 6 horas.',
    motivation:
      'Siempre quise tener una perra y Luna me robó el corazón desde la primera foto. Tenemos jardín y los niños están muy emocionados.',
    additionalInfo: 'Tenemos referencias de una veterinaria cercana.',
  },
  {
    adopterEmail: 'adoptante@adoptame.app',
    petName: 'Nala',
    status: 'reviewing' as const,
    housingType: 'apartment' as const,
    hasYard: false,
    hasPets: false,
    hasChildren: false,
    experience: 'experienced' as const,
    workSchedule: 'Trabajo presencial de 8am a 5pm, pero vivo cerca.',
    motivation:
      'Tuve gatas por más de 10 años. Nala tiene exactamente la personalidad que busco: activa y cariñosa.',
  },
  {
    adopterEmail: 'adoptante@adoptame.app',
    petName: 'Coco',
    status: 'approved' as const,
    housingType: 'house' as const,
    hasYard: true,
    hasPets: false,
    hasChildren: false,
    experience: 'experienced' as const,
    workSchedule: 'Jubilado, estoy en casa la mayor parte del tiempo.',
    motivation:
      'Los perros mayores necesitan más amor que nadie. Tengo tiempo, espacio y ganas de darle a Coco los mejores años de su vida.',
    additionalInfo: 'Soy jubilado y vivo solo. Coco tendría toda mi atención.',
  },
]
